#!/bin/sh

cat > tests/config/tiflash-learner.toml <<eof
[rocksdb]
wal-dir = ""

[security]
ca-path = ""
cert-path = ""
key-path = ""

[server]
addr = "0.0.0.0:20170"
advertise-addr = "127.0.0.1:20170"
engine-addr = "127.0.0.1:3930"
status-addr = "$TIFLASH_STATUS"

[storage]
data-dir = "$TEST_DIR/tiflash/data"
eof

cat > tests/config/tiflash.toml <<eof

default_profile = "default"
display_name = "TiFlash"
http_port = 8123
listen_host = "0.0.0.0"
mark_cache_size = 5368709120
path = "$TEST_DIR/tiflash/data"
tcp_port = 9000
tmp_path = "$TEST_DIR/tiflash-tmp"
capacity = "10737418240"

[application]
runAsDaemon = true

[flash]
service_addr = "127.0.0.1:3930"
tidb_status_addr = "127.0.0.1:10080"
[flash.flash_cluster]
cluster_manager_path = "$PWD/bin/flash_cluster_manager"
log = "$TEST_DIR/tiflash-manager.log"
master_ttl = 60
refresh_interval = 20
update_rule_interval = 5
[flash.proxy]
config = "$PWD/tests/config/tiflash-learner.toml"
log-file = "$TEST_DIR/tiflash-proxy.log"

[logger]
count = 20
errorlog = "$TEST_DIR/tiflash-stderr.log"
level = "debug"
log = "$TEST_DIR/tiflash-stdout.log"
size = "1000M"

[profiles]
[profiles.default]
load_balancing = "random"
max_memory_usage = 10000000000
use_uncompressed_cache = 0
[profiles.readonly]
readonly = 1

[quotas]
[quotas.default]
[quotas.default.interval]
duration = 3600
errors = 0
execution_time = 0
queries = 0
read_rows = 0
result_rows = 0

[raft]
pd_addr = "127.0.0.1:2379"

[status]
metrics_port = 8234

[users]
[users.default]
password = ""
profile = "default"
quota = "default"
[users.default.networks]
ip = "::/0"
[users.readonly]
password = ""
profile = "readonly"
quota = "default"
[users.readonly.networks]
ip = "::/0"
eof