#!/bin/sh
#
# Copyright 2019 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# See the License for the specific language governing permissions and
# limitations under the License.

set -eu

export PD_PEER_ADDR="127.0.0.1:2380"
export PD_ADDR="127.0.0.1:2379"
export TIDB_IP="127.0.0.1"
export TIDB_PORT="4000"
export TIDB_ADDR="127.0.0.1:4000"
export TIDB_STATUS_ADDR="127.0.0.1:10080"
# actual tikv_addr are TIKV_ADDR${i}
export TIKV_ADDR="127.0.0.1:2016"
export TIKV_STATUS_ADDR="127.0.0.1:2018"
export TIKV_COUNT=3
export TIFLASH_STATUS="127.0.0.1:17000"
export TIFLASH_HTTP="127.0.0.1:8125"
export IMPORTER_ADDR="127.0.0.1:8808"

cleanup_data() {
    # Clean up data
    for svc in "br" "tidb" "tiflash" "tikv" "pd" "importer"; do
        find "$TEST_DIR" -maxdepth 1 -name "${svc}*" -type d -exec echo delete {} \; -exec rm -rf {} \; 2> /dev/null
    done
}

stop_services() {
    for svc in "br" "tidb-server" "tiflash" "TiFlashMain" "tikv-server" \
                "pd-server" "cdc" "minio" "tikv-importer" "fake-gcs-server" \
                "oauth"; do
        killall -v -1 $svc 2>/dev/null || continue
        sleep 1 # give some grace shutdown period
        killall -v -9 $svc &>/dev/null || continue
    done
    sleep 1 # give some time for the OS to reap all processes
    lsof -n -P \
        # PD
        -i :2379 \
        # TiDB
        -i :4000 -i :10080 \
        # TiKV
        -i :20161 -i :20162 -i :20163 \
        -i :20181 -i :20182 -i :20183 \
        # TiFlash
        -i :17000 -i :8125
        # fake-gcs-server, oauth and minio
        -i :21808 -i :5000 -i :24927 \
        | awk 'NR > 1 {system("pwdx " $2)}' || true
}

start_services() {
    max_retry=3
    for retry_time in $(seq 1 $max_retry); do
        if start_services_impl $@; then
            return 0
        fi
        stop_services
        echo "Failed to start services, but let's retry it after $(( $retry_time * 30 )) seconds"
        sleep $(( $retry_time * 30 ))
    done
    echo "Failed to start services after retry $max_retry times."
    return 1
}

start_services_impl() {
    stop_services || true
    cleanup_data || true

    TIDB_CONFIG="tests/config/tidb.toml"
    TIKV_CONFIG="tests/config/tikv.toml"
    PD_CONFIG="tests/config/pd.toml"
    RUN_TIFLASH="YES"

    while [[ $# -gt 0 ]]
    do
        local key="$1"

        case $key in
            --tidb-cfg)
            TIDB_CONFIG="$2"
            shift # past argument
            shift # past value
            ;;
            --no-tiflash)
            RUN_TIFLASH="NO"
            shift # past argument
            ;;
            *)    # unknown option
            echo "Unknown args $@"
            exit 1
            ;;
        esac
    done

    echo "Starting PD..."
    mkdir -p "$TEST_DIR/pd"
    bin/pd-server \
        --client-urls "https://$PD_ADDR" \
        --peer-urls "https://$PD_PEER_ADDR" \
        --log-file "$TEST_DIR/pd.log" \
        --data-dir "$TEST_DIR/pd" \
        --config $PD_CONFIG &
    # wait until PD is online...
    i=0
    while ! run_curl "https://$PD_ADDR/pd/api/v1/version"; do
       i=$((i+1))
       if [ "$i" -gt 20 ]; then
          echo 'Failed to start PD'
          return 1
       fi
       sleep 3
    done

    echo "Starting TiKV..."
    for i in $(seq $TIKV_COUNT); do
        mkdir -p "$TEST_DIR/tikv${i}"
        bin/tikv-server \
            --pd "$PD_ADDR" \
            -A "$TIKV_ADDR$i" \
            --status-addr "$TIKV_STATUS_ADDR$i" \
            --log-file "$TEST_DIR/tikv${i}.log" \
            --log-level info \
            -C "$TIKV_CONFIG" \
            -s "$TEST_DIR/tikv${i}" &
    done

    echo "Waiting initializing TiKV..."
    while ! run_curl "https://$PD_ADDR/pd/api/v1/cluster/status" | grep '"is_initialized": true'; do
       i=$((i+1))
       if [ "$i" -gt 20 ]; then
          echo 'Failed to initialize TiKV cluster'
          return 1
       fi
       sleep 5
    done

    echo "Starting TiDB..."
    bin/tidb-server \
        -P 4000 \
        --status 10080 \
        --advertise-address="127.0.0.1" \
        --store tikv \
        --path "$PD_ADDR" \
        --config "$TIDB_CONFIG" \
        --log-file "$TEST_DIR/tidb.log" &

    echo "Verifying TiDB is started..."
    i=0
    while ! run_curl "https://$TIDB_IP:10080/status"; do
        i=$((i+1))
        if [ "$i" -gt 50 ]; then
            echo 'Failed to start TiDB'
            return 1
        fi
        sleep 3
    done

    echo "Starting Importer..."
    bin/tikv-importer \
        --addr "$IMPORTER_ADDR" \
        --import-dir "$TEST_DIR/importer" \
        --log-file "$TEST_DIR/importer.log" \
        --config "tests/config/importer.toml" &

    if [[ $RUN_TIFLASH == "YES" ]]; then
        if ! start_tiflash; then
            return 1
        fi
    fi

    i=0
    while ! run_curl "https://$PD_ADDR/pd/api/v1/cluster/status" | grep -q "\"is_initialized\": true"; do
        i=$((i+1))
        if [ "$i" -gt 20 ]; then
            echo 'Failed to bootstrap cluster'
            return 1
        fi
        sleep 3
    done
}

start_tiflash() {
    echo "Starting TiFlash..."
    tests/_utils/make_tiflash_config
    LD_LIBRARY_PATH=bin/ bin/tiflash server --config-file="$TEST_DIR/tiflash.toml" &

    i=0
    while ! run_curl https://$TIFLASH_HTTP 1>/dev/null 2>&1; do
        i=$((i+1))
        if [ "$i" -gt 20 ]; then
            echo "failed to start tiflash"
            return 1
        fi
        echo "TiFlash seems doesn't started, retrying..."
        sleep 3
    done

    echo "TiFlash started."
}
