linters-settings:
  gocyclo:
    min-complexity: 40
  gocritic:
    disabled-checks:
      - ifElseChain

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      text: "Potential HTTP request made with variable url"
      linters:
        - gosec
