linters-settings:
  gocyclo:
    min-complexity: 40

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: .go
      text: "Potential HTTP request made with variable url"
      linters:
        - gosec
    - path: .go
      text: "Use of weak random number generator"
      linters:
        - gosec
