{
 "title": "Test-Cluster-Backup & Restore",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tikv_engine_size_bytes, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"backup_worker.*\"}[1m]))",
       "legendFormat": "backup-worker"
      },
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{instance=~\"$instance\", name=~\"backup_endpoint\"}[1m]))",
       "legendFormat": "backup-endpoint"
      }
     ]
    },
    {
     "title": "IO Utilization",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_seconds_total[1m])",
       "legendFormat": "{{instance}} - {{device}}"
      }
     ]
    },
    {
     "title": "Backup Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_backup_error_counter[1m])",
       "legendFormat": "{{error}} {{instance}}"
      }
     ]
    },
    {
     "title": "BackupSST Generation Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 8 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(tikv_backup_range_size_bytes_sum[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "One Backup Range Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_backup_range_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, type))",
       "legendFormat": "{{type}} - 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_backup_range_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le, type))",
       "legendFormat": "{{type}} - 95%"
      },
      {
       "expr": "sum(rate(tikv_backup_range_duration_seconds_sum{instance=~\"$instance\"}[1m])) by (type) / sum(rate(tikv_backup_range_duration_seconds_count{instance=~\"$instance\"}[1m])) by (type)",
       "legendFormat": "{{type}} - avg"
      }
     ]
    },
    {
     "title": "One Backup Subtask Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_backup_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": " 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_backup_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "sum(rate(tikv_backup_request_duration_seconds_sum{instance=~\"$instance\"}[1m])) / sum(rate(tikv_backup_request_duration_seconds_count{instance=~\"$instance\"}[1m]))",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Checksum Request Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "legendFormat": "{{req}}-100%"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
       "legendFormat": "{{req}}-99%"
      }
     ]
    }
   ]
  },
  { "title": "Restore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_thread_cpu_seconds_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IO Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "graph",
   "description": " \tThe number of leaders on each TiKV instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tikv_raftstore_region_count{instance=~\"$instance\", type=\"leader\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Region",
   "type": "graph",
   "description": "The number of Regions on each TiKV instance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tikv_raftstore_region_count{instance=~\"$instance\", type=\"region\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process SST Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_import_download_duration_bucket{instance=~\"$instance\"}[1m])) by (le, type))",
     "legendFormat": "{{type}}-99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tikv_import_download_duration_bucket{instance=~\"$instance\"}[1m])) by (le, type))",
     "legendFormat": "{{type}}-95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_import_ingest_duration_bucket{instance=~\"$instance\"}[1m])) by (le, type))",
     "legendFormat": "{{type}}-99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tikv_import_ingest_duration_bucket{instance=~\"$instance\"}[1m])) by (le, type))",
     "legendFormat": "{{type}}-95%"
    }
   ]
  },
  {
   "title": "DownLoad SST Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_import_download_bytes_sum{instance=~\"$instance\"}[1m]))",
     "legendFormat": "download-flow"
    },
    {
     "expr": "rate(tikv_import_download_bytes_sum[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Restore Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ]
  },
  {
   "title": "Checksum Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
     "legendFormat": "{{req}}-100%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_duration_seconds_bucket{instance=~\"$instance\"}[1m])) by (le,req))",
     "legendFormat": "{{req}}-99%"
    }
   ]
  }
 ]
}