// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backup.proto

package meta

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Timestamp struct {
	Physical             int64    `protobuf:"varint,1,opt,name=physical,proto3" json:"physical,omitempty"`
	Logical              int64    `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetPhysical() int64 {
	if m != nil {
		return m.Physical
	}
	return 0
}

func (m *Timestamp) GetLogical() int64 {
	if m != nil {
		return m.Logical
	}
	return 0
}

type BackupMeta struct {
	ClusterVersion       string       `protobuf:"bytes,1,opt,name=cluster_version,json=clusterVersion,proto3" json:"cluster_version,omitempty"`
	IdAlloc              uint64       `protobuf:"varint,2,opt,name=id_alloc,json=idAlloc,proto3" json:"id_alloc,omitempty"`
	SafePoint            *Timestamp   `protobuf:"bytes,3,opt,name=safe_point,json=safePoint,proto3" json:"safe_point,omitempty"`
	Ranges               []*RangeMeta `protobuf:"bytes,4,rep,name=ranges,proto3" json:"ranges,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BackupMeta) Reset()         { *m = BackupMeta{} }
func (m *BackupMeta) String() string { return proto.CompactTextString(m) }
func (*BackupMeta) ProtoMessage()    {}
func (*BackupMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

func (m *BackupMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupMeta.Unmarshal(m, b)
}
func (m *BackupMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupMeta.Marshal(b, m, deterministic)
}
func (m *BackupMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupMeta.Merge(m, src)
}
func (m *BackupMeta) XXX_Size() int {
	return xxx_messageInfo_BackupMeta.Size(m)
}
func (m *BackupMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupMeta.DiscardUnknown(m)
}

var xxx_messageInfo_BackupMeta proto.InternalMessageInfo

func (m *BackupMeta) GetClusterVersion() string {
	if m != nil {
		return m.ClusterVersion
	}
	return ""
}

func (m *BackupMeta) GetIdAlloc() uint64 {
	if m != nil {
		return m.IdAlloc
	}
	return 0
}

func (m *BackupMeta) GetSafePoint() *Timestamp {
	if m != nil {
		return m.SafePoint
	}
	return nil
}

func (m *BackupMeta) GetRanges() []*RangeMeta {
	if m != nil {
		return m.Ranges
	}
	return nil
}

type RangeMeta struct {
	StartKey             []byte     `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey               []byte     `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	CheckPoint           *Timestamp `protobuf:"bytes,3,opt,name=check_point,json=checkPoint,proto3" json:"check_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RangeMeta) Reset()         { *m = RangeMeta{} }
func (m *RangeMeta) String() string { return proto.CompactTextString(m) }
func (*RangeMeta) ProtoMessage()    {}
func (*RangeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

func (m *RangeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RangeMeta.Unmarshal(m, b)
}
func (m *RangeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RangeMeta.Marshal(b, m, deterministic)
}
func (m *RangeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RangeMeta.Merge(m, src)
}
func (m *RangeMeta) XXX_Size() int {
	return xxx_messageInfo_RangeMeta.Size(m)
}
func (m *RangeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_RangeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_RangeMeta proto.InternalMessageInfo

func (m *RangeMeta) GetStartKey() []byte {
	if m != nil {
		return m.StartKey
	}
	return nil
}

func (m *RangeMeta) GetEndKey() []byte {
	if m != nil {
		return m.EndKey
	}
	return nil
}

func (m *RangeMeta) GetCheckPoint() *Timestamp {
	if m != nil {
		return m.CheckPoint
	}
	return nil
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "meta.Timestamp")
	proto.RegisterType((*BackupMeta)(nil), "meta.BackupMeta")
	proto.RegisterType((*RangeMeta)(nil), "meta.RangeMeta")
}

func init() { proto.RegisterFile("backup.proto", fileDescriptor_65240d19de191688) }

var fileDescriptor_65240d19de191688 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x49, 0x1b, 0xf2, 0x73, 0x5b, 0x2c, 0xcc, 0xc6, 0xa8, 0x9b, 0x90, 0x4d, 0xbb, 0x0a,
	0xa2, 0x4f, 0x50, 0xb7, 0x22, 0xc8, 0x20, 0x6e, 0xc3, 0x74, 0x72, 0x6d, 0x87, 0xfc, 0xcc, 0x30,
	0x33, 0x15, 0xf2, 0x48, 0xbe, 0xa5, 0xcc, 0xb5, 0xc6, 0x9d, 0xcb, 0x7b, 0xbe, 0xc3, 0xe1, 0xe3,
	0xc2, 0xfa, 0x20, 0x64, 0x77, 0x36, 0xb5, 0xb1, 0xda, 0x6b, 0x16, 0x0f, 0xe8, 0x45, 0xb5, 0x87,
	0xfc, 0x4d, 0x0d, 0xe8, 0xbc, 0x18, 0x0c, 0xbb, 0x85, 0xcc, 0x9c, 0x26, 0xa7, 0xa4, 0xe8, 0x8b,
	0xa8, 0x8c, 0x76, 0x4b, 0x3e, 0xdf, 0xac, 0x80, 0xb4, 0xd7, 0x47, 0x42, 0x0b, 0x42, 0xbf, 0x67,
	0xf5, 0x15, 0x01, 0x3c, 0xd1, 0xf2, 0x0b, 0x7a, 0xc1, 0xb6, 0xb0, 0x91, 0xfd, 0xd9, 0x79, 0xb4,
	0xcd, 0x27, 0x5a, 0xa7, 0xf4, 0x48, 0x5b, 0x39, 0xbf, 0xba, 0xc4, 0xef, 0x3f, 0x29, 0xbb, 0x81,
	0x4c, 0xb5, 0x8d, 0xe8, 0x7b, 0x2d, 0x69, 0x32, 0xe6, 0xa9, 0x6a, 0xf7, 0xe1, 0x64, 0x35, 0x80,
	0x13, 0x1f, 0xd8, 0x18, 0xad, 0x46, 0x5f, 0x2c, 0xcb, 0x68, 0xb7, 0x7a, 0xd8, 0xd4, 0x41, 0xb8,
	0x9e, 0x6d, 0x79, 0x1e, 0x2a, 0xaf, 0xa1, 0xc1, 0xb6, 0x90, 0x58, 0x31, 0x1e, 0xd1, 0x15, 0x71,
	0xb9, 0xfc, 0xeb, 0xf2, 0x90, 0x05, 0x29, 0x7e, 0xc1, 0x95, 0x83, 0x7c, 0x0e, 0xd9, 0x1d, 0xe4,
	0xce, 0x0b, 0xeb, 0x9b, 0x0e, 0x27, 0x72, 0x5c, 0xf3, 0x8c, 0x82, 0x67, 0x9c, 0xd8, 0x35, 0xa4,
	0x38, 0xb6, 0x84, 0x16, 0x84, 0x12, 0x1c, 0xdb, 0x00, 0xee, 0x61, 0x25, 0x4f, 0x28, 0xbb, 0xff,
	0xe5, 0x80, 0x3a, 0x64, 0x77, 0x48, 0xe8, 0xe1, 0x8f, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x33,
	0x1a, 0x63, 0x2d, 0x80, 0x01, 0x00, 0x00,
}
